### ISSUE TITLE
VCD 9.7 Support

### ISSUE THREAD

**Issue by driseley** [vmware/vcd-api-tools#10]
Are there any plans to release a version with the schemas from VCD 9.7?

Many thanks!

**Comment by jmoroski** [comment]
Apologies for the delayed response.

The short answer is yes. It's on the backlog.

Can you open an issue in the https://github.com/vmware/vcd-api-schemas repository? The api-tools repo is specifically build tooling libraries and utilities. the api-schemas repo is where artifacts for specific product/API versions of vCloud Director are managed. We can track progress there.
